# Generated by Django 6.0.7 on 2026-07-27 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('BANK_TRANSFER', 'Transfer Bank (BCA / BNI / BRI)'), ('EWALLET', 'E-Wallet (GoPay / OVO / Dana)'), ('QRIS', 'QRIS Instant'), ('COD', 'Bayar ditempat (Loket Ticket Box Venue)')], default='QRIS', max_length=50),
        ),
    ]
