# Generated by Django 6.0.7 on 2026-07-26 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ticket_type',
            field=models.CharField(choices=[('REGULAR', 'Regular Pass'), ('VIP', 'VIP Pass (Front Stage + Lineup Meet)'), ('VVIP', 'VVIP Pass (All Access + Lounge & Merchandise)')], default='REGULAR', max_length=20),
        ),
        migrations.AddField(
            model_name='ticket',
            name='ticket_type',
            field=models.CharField(choices=[('REGULAR', 'Regular Pass'), ('VIP', 'VIP Pass (Front Stage + Lineup Meet)'), ('VVIP', 'VVIP Pass (All Access + Lounge & Merchandise)')], default='REGULAR', max_length=20),
        ),
    ]
