# Generated by Django 6.0.7 on 2026-07-26 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_category_id_alter_event_id_alter_order_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ticket_type',
            field=models.CharField(choices=[('REGULAR', 'Regular Pass'), ('VIP', 'VIP Pass (Front Stage + Lineup Meet)'), ('VVIP', 'VVIP Pass (All Access + Lounge & Merchandise)')], default='REGULAR', max_length=20),
        ),
        migrations.AddField(
            model_name='ticket',
            name='ticket_type',
            field=models.CharField(choices=[('REGULAR', 'Regular Pass'), ('VIP', 'VIP Pass (Front Stage + Lineup Meet)'), ('VVIP', 'VVIP Pass (All Access + Lounge & Merchandise)')], default='REGULAR', max_length=20),
        ),
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='event',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
