# Generated by Django 6.0.7 on 2026-07-26 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_order_ticket_type_ticket_ticket_type'),
        ('events', '0003_order_ticket_type_ticket_ticket_type_and_more'),
    ]

    operations = [
    ]
