# Generated by Django 6.0.7 on 2026-07-27 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_order_payment_method'),
        ('events', '0004_merge_20260727_0048'),
    ]

    operations = [
    ]
