# Generated by Django 6.0.7 on 2026-07-27 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_merge_20260727_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('PENDING_APPROVAL', 'Menunggu Persetujuan Admin'), ('UPCOMING', 'Upcoming (Disetujui)'), ('ONGOING', 'Sedang Berlangsung'), ('FINISHED', 'Selesai'), ('CANCELLED', 'Dibatalkan')], default='PENDING_APPROVAL', max_length=25),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('BANK_TRANSFER', 'Transfer Bank (BCA / BNI / BRI)'), ('EWALLET', 'E-Wallet (GoPay / OVO / Dana)'), ('QRIS', 'QRIS Instant'), ('COD', 'Bayar di Tempat (Loket Ticket Box Venue)')], default='QRIS', max_length=50),
        ),
    ]
